version: '3.8'

volumes:

 kibana-data:
   driver: local
 metricbeat-data:
   driver: local
 elasticsearch-data:
   driver: local

networks:
 default:
   name: elastic
   external: false

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=TBnQVpRb67J1AK # Change this password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    volumes:
     - kibana-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD} # Same as Elasticsearch
      - "NODE_OPTIONS=--max-old-space-size=400"
      - XPACK_SECURITY_ENABLED=true
      - SERVER_PUBLICBASEURL=${KIBANA_HOSTS}
    mem_limit: 512m
    depends_on:
      - elasticsearch
  
  metricbeat:
   image: docker.elastic.co/beats/metricbeat:8.17.0
   user: root
   volumes:
     - metricbeat-data:/usr/share/metricbeat/data
     - "./metricbeat.yml:/usr/share/metricbeat/m etricbeat.yml:ro"
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
     - "/proc:/hostfs/proc:ro"
     - "/:/hostfs:ro"
   environment:
     - ELASTIC_USER=${ELASTIC_USER}
     - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
     - ELASTIC_HOSTS=http://elasticsearch:9200
     - KIBANA_HOSTS=http://kibana:5601
   command: ["--environment", "container"]

